steps:
  - name: build-install-locally
    when:
      event: [tag, push]
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean install
      - mvn test -B
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2

  - name: archive-artifact
    when:
      event: [tag, push]
    image: alpine:latest
    commands:
      - mkdir -p /builds/ISEE9660
      - cp target/ISEE9660-*[0-9].jar /builds/ISEE9660/
    volumes:
      - /home/www/builds:/builds
